name: Deploy PR previews
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
    branches:
      - main
concurrency: preview-${{ github.ref }}
jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment variables
        run: |
          echo "REACT_APP_PREVIEW_BASE=pr-${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          echo "REACT_APP_DEPLOY_ENV=PREVIEW" >> $GITHUB_ENV
          echo "REACT_APP_PUBLIC_URL=https://push-protocol.github.io" >> $GITHUB_ENV
          echo "GITHUB_PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          echo "REACT_APP_BASE_URL=/push-website/pr-preview/pr-${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false # Set to true if you're sure tool cache is unnecessary
          android: true # Removes Android SDK (saves ~4GB)
          dotnet: true # Removes .NET Core SDK (saves ~1GB)
          haskell: true # Removes Haskell tools (saves ~1GB)
          large-packages: true # Removes large packages
          docker-images: true # Removes unused Docker images
          swap-storage: true # Removes swap files

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: yarn

      - name: Clean yarn cache
        run: yarn cache clean --force
      # - run: yarn ci

      - name: Install and Build
        if: github.event.action != 'closed' # You might want to skip the build if the PR has been closed
        run: |
          yarn install
          yarn build:pr:preview

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1.4.7
        with:
          source-dir: ./build/
          umbrella-dir: pr-preview

      - uses: rossjrw/pr-preview-action@v1.4.7
        if: github.event.action == 'closed' && !github.event.pull_request.merged
        with:
          source-dir: ./build/
          action: remove
